export const vehicleModels: Record<string, string[]> = {
  Acura: ["MDX", "RDX", "TLX", "Integra", "ZDX", "Other"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8", "e-tron", "Other"],
  BMW: ["3 Series", "5 Series", "X1", "X3", "X5", "X7", "i4", "iX", "Other"],
  Buick: ["Enclave", "Encore", "Envision", "Other"],
  Cadillac: ["XT4", "XT5", "XT6", "Escalade", "CT5", "Lyriq", "Other"],
  Chevrolet: [
    "Silverado",
    "Equinox",
    "Tahoe",
    "Suburban",
    "Traverse",
    "Camaro",
    "Corvette",
    "Colorado",
    "Bolt",
    "Other",
  ],
  Chrysler: ["300", "Pacifica", "Other"],
  Dodge: ["Charger", "Challenger", "Durango", "Other"],
  Ford: [
    "F-150",
    "F-250",
    "F-350",
    "Explorer",
    "Bronco",
    "Bronco Sport",
    "Escape",
    "Mustang",
    "Edge",
    "Maverick",
    "Ranger",
    "Expedition",
    "Other",
  ],
  GMC: ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon", "Hummer EV", "Other"],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Pilot",
    "Odyssey",
    "Passport",
    "Ridgeline",
    "HR-V",
    "Other",
  ],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Kona",
    "Ioniq 5",
    "Other",
  ],
  Jeep: [
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Compass",
    "Gladiator",
    "Wagoneer",
    "Grand Wagoneer",
    "Other",
  ],
  Kia: ["Sorento", "Telluride", "Sportage", "Soul", "K5", "EV6", "Other"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Range Rover",
    "Range Rover Sport",
    "Other",
  ],
  Lexus: ["RX", "GX", "LX", "ES", "NX", "IS", "TX", "Other"],
  Lincoln: ["Navigator", "Aviator", "Nautilus", "Corsair", "Other"],
  Mazda: ["CX-5", "CX-9", "CX-50", "CX-90", "Mazda3", "MX-5", "Other"],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "EQS",
    "Sprinter",
    "Other",
  ],
  Mini: ["Cooper", "Countryman", "Other"],
  Mitsubishi: ["Outlander", "Eclipse Cross", "Other"],
  Nissan: [
    "Altima",
    "Maxima",
    "Sentra",
    "Rogue",
    "Murano",
    "Pathfinder",
    "Frontier",
    "Titan",
    "Other",
  ],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Other"],
  Ram: ["1500", "2500", "3500", "ProMaster", "Other"],
  Rivian: ["R1T", "R1S", "Other"],
  Subaru: [
    "Outback",
    "Forester",
    "Crosstrek",
    "Ascent",
    "Impreza",
    "Legacy",
    "WRX",
    "Other",
  ],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Other"],
  Toyota: [
    "4Runner",
    "Camry",
    "Corolla",
    "RAV4",
    "Tacoma",
    "Tundra",
    "Highlander",
    "Sequoia",
    "Sienna",
    "Prius",
    "Land Cruiser",
    "Other",
  ],
  Volkswagen: ["Atlas", "Tiguan", "Jetta", "Passat", "Golf", "ID.4", "Other"],
  Volvo: ["XC40", "XC60", "XC90", "S60", "S90", "Other"],
  Other: ["Other"],
};

export const vehicleMakes = Object.keys(vehicleModels).sort((a, b) => {
  if (a === "Other") return 1;
  if (b === "Other") return -1;
  return a.localeCompare(b);
});

export const vehicleYears = (() => {
  const current = new Date().getFullYear();
  const out: number[] = [];
  for (let y = current + 1; y >= 1990; y--) out.push(y);
  return out;
})();
