export const vehicleModels: Record<string, string[]> = {
  Acura: [
    "CL",
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX",
    "Other",
  ],
  "Alfa Romeo": [
    "4C",
    "8C Competizione",
    "Giulia",
    "Giulietta",
    "GT",
    "MiTo",
    "Spider",
    "Stelvio",
    "Tonale",
    "Other",
  ],
  "Aston Martin": [
    "Cygnet",
    "DB7",
    "DB9",
    "DB11",
    "DB12",
    "DBS",
    "DBS Superleggera",
    "DBX",
    "One-77",
    "Rapide",
    "Valhalla",
    "Valkyrie",
    "Vantage",
    "Vanquish",
    "Virage",
    "Other",
  ],
  Audi: [
    "80",
    "90",
    "100",
    "200",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "allroad",
    "Cabriolet",
    "e-tron",
    "e-tron GT",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q5 e-tron",
    "Q7",
    "Q8",
    "Q8 e-tron",
    "Quattro",
    "R8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "RS Q3",
    "RS Q8",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "SQ7",
    "SQ8",
    "TT",
    "TTS",
    "TT RS",
    "V8",
    "Other",
  ],
  Bentley: [
    "Arnage",
    "Azure",
    "Bentayga",
    "Bentayga EWB",
    "Brooklands",
    "Continental Flying Spur",
    "Continental GT",
    "Continental GTC",
    "Flying Spur",
    "Mulsanne",
    "Other",
  ],
  BMW: [
    "1 Series",
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "Alpina B7",
    "Alpina XB7",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX",
    "iX1",
    "iX3",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M8",
    "X1",
    "X2",
    "X3",
    "X3 M",
    "X4",
    "X5",
    "X5 M",
    "X6",
    "X6 M",
    "X7",
    "XM",
    "Z3",
    "Z4",
    "Z8",
    "Other",
  ],
  Buick: [
    "Cascada",
    "Century",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Envista",
    "LaCrosse",
    "LeSabre",
    "Lucerne",
    "Park Avenue",
    "Rainier",
    "Reatta",
    "Regal",
    "Rendezvous",
    "Riviera",
    "Roadmaster",
    "Skylark",
    "Terraza",
    "Verano",
    "Other",
  ],
  Cadillac: [
    "Allante",
    "ATS",
    "Brougham",
    "Catera",
    "Celestiq",
    "Cimarron",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "DeVille",
    "DTS",
    "Eldorado",
    "ELR",
    "Escalade",
    "Escalade ESV",
    "Escalade EXT",
    "Fleetwood",
    "Lyriq",
    "Seville",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
    "XTS",
    "Other",
  ],
  Chevrolet: [
    "Astro",
    "Avalanche",
    "Aveo",
    "Bel Air",
    "Beretta",
    "Blazer",
    "Bolt EUV",
    "Bolt EV",
    "C/K (heritage)",
    "Camaro",
    "Caprice",
    "Cavalier",
    "Chevelle",
    "Citation",
    "Cobalt",
    "Colorado",
    "Corsica",
    "Corvair",
    "Corvette",
    "Cruze",
    "El Camino",
    "Equinox",
    "Express",
    "HHR",
    "Impala",
    "Lumina",
    "Malibu",
    "Metro",
    "Monte Carlo",
    "Nova",
    "S-10",
    "Silverado",
    "Sonic",
    "Spark",
    "SS",
    "SSR",
    "Suburban",
    "Tahoe",
    "Tracker",
    "Trailblazer",
    "Traverse",
    "Trax",
    "Uplander",
    "Venture",
    "Volt",
    "Other",
  ],
  Chrysler: [
    "200",
    "300",
    "300M",
    "Aspen",
    "Cirrus",
    "Concorde",
    "Crossfire",
    "Imperial",
    "LeBaron",
    "LHS",
    "New Yorker",
    "Pacifica",
    "PT Cruiser",
    "Sebring",
    "Town & Country",
    "Voyager",
    "Other",
  ],
  Dodge: [
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger",
    "Charger",
    "Dakota",
    "Dart",
    "Durango",
    "Grand Caravan",
    "Hornet",
    "Intrepid",
    "Journey",
    "Magnum",
    "Neon",
    "Nitro",
    "Ram",
    "Ramcharger",
    "Shadow",
    "Spirit",
    "Stealth",
    "Stratus",
    "Viper",
    "Other",
  ],
  Ferrari: [
    "296 GTB",
    "308",
    "328",
    "348",
    "355",
    "360",
    "430",
    "458",
    "488",
    "550",
    "575",
    "599",
    "612",
    "812 Superfast",
    "California",
    "Daytona SP3",
    "Enzo",
    "F8 Tributo",
    "F12",
    "F40",
    "F50",
    "FF",
    "GTC4Lusso",
    "LaFerrari",
    "Mondial",
    "Portofino",
    "Purosangue",
    "Roma",
    "SF90 Stradale",
    "Testarossa",
    "Other",
  ],
  Fiat: ["124 Spider", "500", "500c", "500e", "500L", "500X", "Panda", "Other"],
  Ford: [
    "Aerostar",
    "Aspire",
    "Bronco",
    "Bronco Sport",
    "C-Max",
    "Contour",
    "Crown Victoria",
    "E-150",
    "E-250",
    "E-350",
    "E-Series",
    "EcoSport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Explorer",
    "Explorer Sport Trac",
    "F-150",
    "F-150 Lightning",
    "F-250",
    "F-350",
    "F-450",
    "F-650",
    "Fairmont",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Freestar",
    "Freestyle",
    "Fusion",
    "Galaxie",
    "GT",
    "Granada",
    "Maverick",
    "Mustang",
    "Mustang Mach-E",
    "Pinto",
    "Probe",
    "Ranger",
    "Shelby GT500",
    "Taurus",
    "Tempo",
    "Thunderbird",
    "Torino",
    "Transit",
    "Transit Connect",
    "Windstar",
    "Other",
  ],
  Genesis: ["Coupe", "G70", "G80", "G90", "GV60", "GV70", "GV80", "Other"],
  GMC: [
    "Acadia",
    "Canyon",
    "Envoy",
    "Hummer EV Pickup",
    "Hummer EV SUV",
    "Jimmy",
    "Safari",
    "Savana",
    "Sierra",
    "Sierra 1500",
    "Sierra 2500",
    "Sierra 3500",
    "Sonoma",
    "Suburban",
    "Syclone",
    "Terrain",
    "Topkick",
    "Typhoon",
    "Vandura",
    "Yukon",
    "Yukon XL",
    "Other",
  ],
  Honda: [
    "Accord",
    "Civic",
    "Civic Si",
    "Civic Type R",
    "Clarity",
    "CR-V",
    "CR-Z",
    "Crosstour",
    "del Sol",
    "Element",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Prologue",
    "Ridgeline",
    "S2000",
    "Other",
  ],
  Hummer: ["H1", "H2", "H2 SUT", "H3", "H3T", "Other"],
  Hyundai: [
    "Accent",
    "Azera",
    "Elantra",
    "Elantra GT",
    "Elantra N",
    "Entourage",
    "Equus",
    "Genesis Coupe",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 5 N",
    "Ioniq 6",
    "Kona",
    "Kona Electric",
    "Nexo",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Sonata",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Venue",
    "Veracruz",
    "Other",
  ],
  Infiniti: [
    "EX35",
    "EX37",
    "FX35",
    "FX37",
    "FX45",
    "FX50",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "J30",
    "JX35",
    "M30",
    "M35",
    "M37",
    "M45",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX4",
    "QX30",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX70",
    "QX80",
    "Other",
  ],
  Isuzu: [
    "Amigo",
    "Ascender",
    "Axiom",
    "Hombre",
    "i-280",
    "i-290",
    "i-350",
    "i-370",
    "Oasis",
    "Pickup",
    "Rodeo",
    "Rodeo Sport",
    "Stylus",
    "Trooper",
    "VehiCROSS",
    "Other",
  ],
  Jaguar: [
    "E-Pace",
    "E-Type",
    "F-Pace",
    "F-Type",
    "I-Pace",
    "S-Type",
    "X-Type",
    "XE",
    "XF",
    "XJ",
    "XJR",
    "XK",
    "XKR",
    "Other",
  ],
  Jeep: [
    "Cherokee",
    "CJ-5",
    "CJ-7",
    "Comanche",
    "Commander",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Cherokee L",
    "Grand Wagoneer",
    "Liberty",
    "Patriot",
    "Renegade",
    "Scrambler",
    "Wagoneer",
    "Willys",
    "Wrangler",
    "Wrangler 4xe",
    "Wrangler Unlimited",
    "Other",
  ],
  Kia: [
    "Amanti",
    "Borrego",
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "K5",
    "K900",
    "Niro",
    "Niro EV",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sorento",
    "Soul",
    "Soul EV",
    "Spectra",
    "Sportage",
    "Stinger",
    "Telluride",
    "Other",
  ],
  Lamborghini: [
    "Aventador",
    "Centenario",
    "Countach",
    "Diablo",
    "Espada",
    "Gallardo",
    "Huracan",
    "Jalpa",
    "LM002",
    "Miura",
    "Murcielago",
    "Reventon",
    "Revuelto",
    "Sesto Elemento",
    "Sian",
    "Temerario",
    "Urus",
    "Veneno",
    "Other",
  ],
  "Land Rover": [
    "Defender",
    "Defender 90",
    "Defender 110",
    "Defender 130",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
    "Series II",
    "Series III",
    "Other",
  ],
  Lexus: [
    "CT",
    "ES",
    "GS",
    "GS F",
    "GX",
    "HS",
    "IS",
    "IS F",
    "LC",
    "LFA",
    "LS",
    "LX",
    "NX",
    "RC",
    "RC F",
    "RX",
    "RX L",
    "RZ",
    "SC",
    "TX",
    "UX",
    "Other",
  ],
  Lincoln: [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "Mark LT",
    "Mark VII",
    "Mark VIII",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Nautilus",
    "Navigator",
    "Navigator L",
    "Town Car",
    "Versailles",
    "Zephyr",
    "Other",
  ],
  Lotus: [
    "2-Eleven",
    "3-Eleven",
    "Cortina",
    "Eclat",
    "Elan",
    "Eletre",
    "Elise",
    "Emeya",
    "Emira",
    "Esprit",
    "Europa",
    "Evija",
    "Evora",
    "Excel",
    "Exige",
    "Seven",
    "Other",
  ],
  Lucid: ["Air", "Air Grand Touring", "Air Pure", "Air Sapphire", "Air Touring", "Gravity", "Other"],
  Maserati: [
    "3200 GT",
    "4200 GT",
    "BiTurbo",
    "Bora",
    "Coupé",
    "Ghibli",
    "GranCabrio",
    "GranTurismo",
    "Grecale",
    "Levante",
    "MC12",
    "MC20",
    "Quattroporte",
    "Spyder",
    "Other",
  ],
  Mazda: [
    "2",
    "3",
    "5",
    "6",
    "626",
    "929",
    "B-Series",
    "Cosmo",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-7",
    "CX-9",
    "CX-90",
    "Mazdaspeed3",
    "Mazdaspeed6",
    "Millenia",
    "MPV",
    "MX-5 Miata",
    "MX-30",
    "Protege",
    "RX-7",
    "RX-8",
    "Tribute",
    "Other",
  ],
  McLaren: [
    "12C",
    "540C",
    "570GT",
    "570S",
    "600LT",
    "620R",
    "650S",
    "675LT",
    "720S",
    "750S",
    "765LT",
    "Artura",
    "Elva",
    "F1",
    "GT",
    "MP4-12C",
    "P1",
    "Senna",
    "Solus GT",
    "Speedtail",
    "Other",
  ],
  "Mercedes-Benz": [
    "190",
    "190SL",
    "280SL",
    "300",
    "400",
    "500",
    "600",
    "A-Class",
    "AMG GT",
    "B-Class",
    "C-Class",
    "CL-Class",
    "CLA",
    "CLK",
    "CLS",
    "E-Class",
    "EQB",
    "EQE",
    "EQE SUV",
    "EQS",
    "EQS SUV",
    "G-Class",
    "GL-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLK",
    "GLS",
    "Maybach",
    "Metris",
    "ML-Class",
    "R-Class",
    "S-Class",
    "SL-Class",
    "SLC",
    "SLK",
    "SLR McLaren",
    "SLS AMG",
    "Sprinter",
    "Other",
  ],
  Mercury: [
    "Bobcat",
    "Capri",
    "Comet",
    "Cougar",
    "Grand Marquis",
    "Lynx",
    "Marauder",
    "Mariner",
    "Marquis",
    "Milan",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
    "Zephyr",
    "Other",
  ],
  Mini: [
    "Clubman",
    "Convertible",
    "Cooper",
    "Cooper Countryman",
    "Cooper Hardtop",
    "Cooper SE",
    "Coupe",
    "Countryman",
    "John Cooper Works",
    "Paceman",
    "Roadster",
    "Other",
  ],
  Mitsubishi: [
    "3000GT",
    "Cordia",
    "Diamante",
    "Eclipse",
    "Eclipse Cross",
    "Endeavor",
    "Galant",
    "i-MiEV",
    "Lancer",
    "Lancer Evolution",
    "Mirage",
    "Mirage G4",
    "Montero",
    "Montero Sport",
    "Outlander",
    "Outlander PHEV",
    "Outlander Sport",
    "Raider",
    "Starion",
    "Other",
  ],
  Nissan: [
    "200SX",
    "240SX",
    "300ZX",
    "350Z",
    "370Z",
    "Altima",
    "Ariya",
    "Armada",
    "Cube",
    "Frontier",
    "GT-R",
    "Hardbody",
    "Juke",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "NV200",
    "NV1500",
    "NV2500",
    "NV3500",
    "Pathfinder",
    "Pickup",
    "Pulsar",
    "Quest",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Stanza",
    "Titan",
    "Titan XD",
    "Versa",
    "Versa Note",
    "Xterra",
    "Z",
    "Other",
  ],
  Oldsmobile: [
    "88",
    "98",
    "Achieva",
    "Alero",
    "Aurora",
    "Bravada",
    "Calais",
    "Custom Cruiser",
    "Cutlass",
    "Cutlass Calais",
    "Cutlass Ciera",
    "Cutlass Supreme",
    "Delta 88",
    "Firenza",
    "Intrigue",
    "LSS",
    "Omega",
    "Regency",
    "Silhouette",
    "Toronado",
    "Vista Cruiser",
    "Other",
  ],
  Plymouth: [
    "Acclaim",
    "Barracuda",
    "Breeze",
    "Colt",
    "Duster",
    "Fury",
    "GTX",
    "Horizon",
    "Laser",
    "Neon",
    "Prowler",
    "Reliant",
    "Roadrunner",
    "Sundance",
    "Trailduster",
    "Valiant",
    "Voyager",
    "Other",
  ],
  Polestar: ["1", "2", "3", "4", "5", "6", "Other"],
  Pontiac: [
    "6000",
    "Aztek",
    "Bonneville",
    "Catalina",
    "Fiero",
    "Firebird",
    "G3",
    "G5",
    "G6",
    "G8",
    "Grand Am",
    "Grand Prix",
    "GTO",
    "LeMans",
    "Montana",
    "Parisienne",
    "Phoenix",
    "Pursuit",
    "Solstice",
    "Sunbird",
    "Sunfire",
    "T-1000",
    "Torrent",
    "Trans Am",
    "Trans Sport",
    "Vibe",
    "Other",
  ],
  Porsche: [
    "356",
    "718 Boxster",
    "718 Cayman",
    "718 Spyder",
    "911",
    "911 GT2",
    "911 GT3",
    "911 GT3 RS",
    "911 Turbo",
    "914",
    "918 Spyder",
    "924",
    "928",
    "944",
    "968",
    "Boxster",
    "Carrera GT",
    "Cayenne",
    "Cayman",
    "Macan",
    "Macan EV",
    "Panamera",
    "Taycan",
    "Other",
  ],
  Ram: [
    "1500",
    "1500 Classic",
    "1500 TRX",
    "2500",
    "3500",
    "4500",
    "5500",
    "Dakota",
    "ProMaster",
    "ProMaster City",
    "Other",
  ],
  Rivian: ["R1S", "R1T", "R2", "R3", "EDV", "Other"],
  "Rolls-Royce": [
    "Corniche",
    "Cullinan",
    "Dawn",
    "Ghost",
    "Phantom",
    "Phantom Coupe",
    "Phantom Drophead Coupe",
    "Silver Seraph",
    "Silver Shadow",
    "Silver Spirit",
    "Silver Spur",
    "Silver Wraith",
    "Spectre",
    "Wraith",
    "Other",
  ],
  Saab: ["9-2X", "9-3", "9-4X", "9-5", "9-7X", "92", "96", "99", "900", "Other"],
  Saturn: [
    "Astra",
    "Aura",
    "Ion",
    "L-Series",
    "Outlook",
    "Relay",
    "S-Series",
    "SC",
    "Sky",
    "SL",
    "SW",
    "Vue",
    "Other",
  ],
  Scion: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD", "Other"],
  Smart: ["Fortwo", "Fortwo Electric Drive", "Forfour", "Roadster", "Other"],
  Subaru: [
    "Ascent",
    "B9 Tribeca",
    "Baja",
    "Brat",
    "BRZ",
    "Crosstrek",
    "Forester",
    "GL",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Outback",
    "Solterra",
    "SVX",
    "Tribeca",
    "WRX",
    "WRX STI",
    "XT",
    "XV Crosstrek",
    "Other",
  ],
  Suzuki: [
    "Aerio",
    "Equator",
    "Esteem",
    "Forenza",
    "Grand Vitara",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "Swift",
    "SX4",
    "Verona",
    "Vitara",
    "X-90",
    "XL-7",
    "Other",
  ],
  Tesla: [
    "Cybertruck",
    "Model 3",
    "Model 3 Performance",
    "Model S",
    "Model S Plaid",
    "Model X",
    "Model X Plaid",
    "Model Y",
    "Roadster",
    "Roadster (new)",
    "Semi",
    "Other",
  ],
  Toyota: [
    "4Runner",
    "86",
    "Avalon",
    "bZ4X",
    "C-HR",
    "Camry",
    "Celica",
    "Corolla",
    "Corolla Cross",
    "Corolla Hatchback",
    "Crown",
    "Crown Signia",
    "Echo",
    "FJ Cruiser",
    "GR86",
    "GR Corolla",
    "GR Supra",
    "Grand Highlander",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Paseo",
    "Previa",
    "Prius",
    "Prius Prime",
    "RAV4",
    "RAV4 Prime",
    "Sequoia",
    "Sienna",
    "Solara",
    "Starlet",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Tundra",
    "Venza",
    "Yaris",
    "Other",
  ],
  VinFast: ["VF6", "VF7", "VF8", "VF9", "Other"],
  Volkswagen: [
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Beetle",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "Eos",
    "EuroVan",
    "Fox",
    "GLI",
    "Golf",
    "Golf R",
    "GTI",
    "ID. Buzz",
    "ID.4",
    "Jetta",
    "Karmann Ghia",
    "New Beetle",
    "Passat",
    "Phaeton",
    "R32",
    "Rabbit",
    "Routan",
    "Scirocco",
    "Taos",
    "Tiguan",
    "Touareg",
    "Vanagon",
    "Other",
  ],
  Volvo: [
    "240",
    "740",
    "760",
    "850",
    "940",
    "960",
    "C30",
    "C40",
    "C70",
    "EX30",
    "EX90",
    "S40",
    "S60",
    "S70",
    "S80",
    "S90",
    "V40",
    "V50",
    "V60",
    "V70",
    "V90",
    "V90 Cross Country",
    "XC40",
    "XC60",
    "XC70",
    "XC90",
    "Other",
  ],
  Other: ["Other"],
};

export const vehicleMakes = Object.keys(vehicleModels).sort((a, b) => {
  if (a === "Other") return 1;
  if (b === "Other") return -1;
  return a.localeCompare(b);
});

export const vehicleYears = (() => {
  const current = new Date().getFullYear();
  const out: number[] = [];
  for (let y = current + 1; y >= 1990; y--) out.push(y);
  return out;
})();
