export const vehicleModels: Record<string, string[]> = {
  Acura: ["MDX", "RDX", "TLX", "Integra", "ZDX", "ILX", "NSX", "Other"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C", "Other"],
  "Aston Martin": ["DB11", "DB12", "Vantage", "DBX", "DBS", "Other"],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "e-tron",
    "RS",
    "S",
    "TT",
    "R8",
    "Other",
  ],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Other"],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "7 Series",
    "8 Series",
    "X1",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "i4",
    "iX",
    "M",
    "Z4",
    "Other",
  ],
  Buick: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal", "Other"],
  Cadillac: [
    "XT4",
    "XT5",
    "XT6",
    "Escalade",
    "CT4",
    "CT5",
    "Lyriq",
    "Celestiq",
    "Other",
  ],
  Chevrolet: [
    "Silverado",
    "Equinox",
    "Tahoe",
    "Suburban",
    "Traverse",
    "Blazer",
    "Trailblazer",
    "Trax",
    "Camaro",
    "Corvette",
    "Colorado",
    "Malibu",
    "Bolt",
    "Other",
  ],
  Chrysler: ["300", "Pacifica", "Voyager", "Other"],
  Dodge: ["Charger", "Challenger", "Durango", "Hornet", "Journey", "Other"],
  Ferrari: [
    "458",
    "488",
    "F8 Tributo",
    "SF90",
    "296",
    "Roma",
    "Portofino",
    "812",
    "Purosangue",
    "Other",
  ],
  Fiat: ["500", "500X", "124 Spider", "Other"],
  Ford: [
    "F-150",
    "F-250",
    "F-350",
    "Explorer",
    "Bronco",
    "Bronco Sport",
    "Escape",
    "Mustang",
    "Mustang Mach-E",
    "Edge",
    "Maverick",
    "Ranger",
    "Expedition",
    "Transit",
    "Other",
  ],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "Other"],
  GMC: [
    "Sierra",
    "Yukon",
    "Acadia",
    "Terrain",
    "Canyon",
    "Hummer EV",
    "Savana",
    "Other",
  ],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Pilot",
    "Odyssey",
    "Passport",
    "Ridgeline",
    "HR-V",
    "Fit",
    "Prologue",
    "Other",
  ],
  Hummer: ["H1", "H2", "H3", "Other"],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Kona",
    "Venue",
    "Ioniq 5",
    "Ioniq 6",
    "Other",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80", "Other"],
  Isuzu: ["Trooper", "Rodeo", "Ascender", "Other"],
  Jaguar: ["F-Pace", "E-Pace", "I-Pace", "XF", "XE", "F-Type", "Other"],
  Jeep: [
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Compass",
    "Gladiator",
    "Renegade",
    "Wagoneer",
    "Grand Wagoneer",
    "Other",
  ],
  Kia: [
    "Sorento",
    "Telluride",
    "Sportage",
    "Soul",
    "Forte",
    "K5",
    "Carnival",
    "EV6",
    "EV9",
    "Niro",
    "Other",
  ],
  Lamborghini: ["Huracan", "Aventador", "Urus", "Revuelto", "Other"],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
    "Range Rover Evoque",
    "Other",
  ],
  Lexus: [
    "RX",
    "GX",
    "LX",
    "ES",
    "NX",
    "IS",
    "TX",
    "UX",
    "LS",
    "RC",
    "LC",
    "Other",
  ],
  Lincoln: ["Navigator", "Aviator", "Nautilus", "Corsair", "Other"],
  Lotus: ["Emira", "Evora", "Eletre", "Other"],
  Lucid: ["Air", "Gravity", "Other"],
  Maserati: ["Ghibli", "Levante", "Quattroporte", "MC20", "Grecale", "Other"],
  Mazda: [
    "CX-3",
    "CX-5",
    "CX-9",
    "CX-30",
    "CX-50",
    "CX-90",
    "Mazda3",
    "MX-5",
    "Other",
  ],
  McLaren: ["720S", "750S", "765LT", "Artura", "GT", "Other"],
  "Mercedes-Benz": [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "AMG GT",
    "EQS",
    "EQE",
    "Sprinter",
    "Other",
  ],
  Mercury: ["Grand Marquis", "Mountaineer", "Sable", "Cougar", "Other"],
  Mini: ["Cooper", "Countryman", "Clubman", "Other"],
  Mitsubishi: [
    "Outlander",
    "Outlander Sport",
    "Eclipse Cross",
    "Mirage",
    "Other",
  ],
  Nissan: [
    "Altima",
    "Maxima",
    "Sentra",
    "Versa",
    "Rogue",
    "Murano",
    "Pathfinder",
    "Armada",
    "Frontier",
    "Titan",
    "Leaf",
    "Ariya",
    "Z",
    "GT-R",
    "Other",
  ],
  Oldsmobile: ["Cutlass", "88", "98", "Alero", "Bravada", "Other"],
  Plymouth: ["Barracuda", "Roadrunner", "GTX", "Prowler", "Other"],
  Polestar: ["1", "2", "3", "4", "Other"],
  Pontiac: ["GTO", "Firebird", "Trans Am", "G6", "Grand Am", "Solstice", "Other"],
  Porsche: [
    "911",
    "718 Cayman",
    "718 Boxster",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "Other",
  ],
  Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City", "Other"],
  Rivian: ["R1T", "R1S", "Other"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan", "Spectre", "Dawn", "Other"],
  Saab: ["9-3", "9-5", "9-7X", "900", "Other"],
  Saturn: ["Ion", "Aura", "Vue", "Outlook", "Sky", "Other"],
  Scion: ["tC", "xB", "xD", "FR-S", "iQ", "Other"],
  Smart: ["Fortwo", "Forfour", "Other"],
  Subaru: [
    "Outback",
    "Forester",
    "Crosstrek",
    "Ascent",
    "Impreza",
    "Legacy",
    "WRX",
    "BRZ",
    "Solterra",
    "Other",
  ],
  Suzuki: ["Samurai", "Sidekick", "Vitara", "SX4", "Other"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Roadster", "Other"],
  Toyota: [
    "4Runner",
    "Camry",
    "Corolla",
    "RAV4",
    "Tacoma",
    "Tundra",
    "Highlander",
    "Sequoia",
    "Sienna",
    "Prius",
    "Avalon",
    "Crown",
    "Land Cruiser",
    "GR Corolla",
    "GR86",
    "GR Supra",
    "bZ4X",
    "Other",
  ],
  VinFast: ["VF8", "VF9", "Other"],
  Volkswagen: [
    "Atlas",
    "Atlas Cross Sport",
    "Tiguan",
    "Taos",
    "Jetta",
    "Passat",
    "Golf",
    "GTI",
    "Golf R",
    "ID.4",
    "Arteon",
    "Other",
  ],
  Volvo: [
    "XC40",
    "XC60",
    "XC90",
    "S60",
    "S90",
    "V60",
    "V90",
    "C40",
    "EX30",
    "EX90",
    "Other",
  ],
  Other: ["Other"],
};

export const vehicleMakes = Object.keys(vehicleModels).sort((a, b) => {
  if (a === "Other") return 1;
  if (b === "Other") return -1;
  return a.localeCompare(b);
});

export const vehicleYears = (() => {
  const current = new Date().getFullYear();
  const out: number[] = [];
  for (let y = current + 1; y >= 1990; y--) out.push(y);
  return out;
})();
